# Numpy

In [2]:
import numpy as np

## 簡単な計算

In [3]:
ary = np.array([
    [1, 2, 3],
    [4, 5, 6]])
ary

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
print("次元数：", ary.ndim)
print("要素数：", ary.size)
print("行列："   , ary.shape)
print("行："      , ary.shape[0])
print("列："      , ary.shape[1])

次元数： 2
要素数： 6
行列： (2, 3)
行： 2
列： 3


行列のドット積（単なる積）も定義することができる。

In [9]:
matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6]])

matrix2 = np.array([
    [7, 8, 9],
    [10, 11, 12]])

np.dot(matrix1, matrix2.T)

# 2×3行列と2×3行列の積は、計算できない（行列の計算と同じ）
# np.dot(matrix1, matrix2) 

array([[ 50,  68],
       [122, 167]])

もちろんベクトルのドット積も定義することができ、それは通常の通り要素の二乗和になる。

In [10]:
row_vector = np.array([1,2,3,4])
np.dot(row_vector.T, row_vector)

30

In [11]:
np.random.seed(123)
ary = np.array(np.random.randn(5,2))
ary

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654],
       [-2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 ]])

## Reshaping Arrays 

1次元の配列を行列に変換する。また行or列のどちらかを指定すれば片方も決定するので、引数に与える数字も片方だけでよい。その場合は-1を与える。

In [ ]:
ary1d = np.array([1,2,3,4,5,6])
ary1d.reshape(2,3)

In [ ]:
ary1d.reshape(2,-1)

In [ ]:
ary1d.reshape(-1,3)

また2次元の行列をすべて1次元にすることも可能で、`ravel`（解きほぐす）関数を使う。

In [ ]:
ary2d = np.array(
    [[1,2,3],
    [4,5,6],])
ary2d.ravel()

# グリッド

In [ ]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([6,7,8,9,10])

x1_min, x1_max = x1.min(), x1.max()
x2_min, x2_max = x2.min(), x2.max()

xx1, xx2 = np.meshgrid(
    np.arange(x1_min, x1_max, 0.02), # x1_minからx1_maxまで0.02刻みで配列を作る
    np.arange(x2_min, x2_max, 0.02), # x2_minからx2_maxまで0.02刻みで配列を作る
                      )

In [ ]:
np.arange(x1_min, x1_max, 0.02),

## その他
### クリッピング `clip`

In [ ]:
# 第二引数〜第三引数の範囲にまとめるメソッド（ヒストグラムのunderflow bin, overflow bin として捉えれば分かりやすいかな）
ary_old = np.array([1,2,3,4,5,6,7])
ary_new = np.clip(ary, 2,5)
print(ary_old, "--->", ary_new)

### 論理和 `logical_`

In [ ]:
X_xor = np.random.randn(5,2)
print(X_xor)

# 両方が正になる場合にTrue（AND）
print(np.logical_and(X_xor[:,0]>0, X_xor[:, 1]>0))

# 一方が正になる場合にTrue（OR）
print(np.logical_or(X_xor[:,0]>0, X_xor[:, 1]>0))

# 配列の一方だけが正になる場合をTrueとする（XOR　排他的論理和）
print(np.logical_xor(X_xor[:,0]>0, X_xor[:, 1]>0))

### 平坦化

In [ ]:
x1 = np.arange(0, 10, 1)
print(x1.reshape(-1,2))
print(x1.reshape(-1,2).ravel())

In [ ]:
print(np.array([x1.ravel(), x1.ravel()]))
print(np.array([x1.ravel(), x1.ravel()]).shape)

In [ ]:
print(np.array([x1, x1]))
print(np.array([x1, x1]).shape)

In [ ]:
print(np.array([x1, x1, x1]))
print(np.array([x1, x1, x1]).shape)

In [ ]:
print(np.array([x1, x1, x1]).T)
print(np.array([x1, x1, x1]).T.shape)